### ISSUE TITLE
Reproduce the scores

### ISSUE THREAD

**Issue by mengruwu** [honghanhh/terminology-extraction#9]
Hi, I want to thank you for sharing the code and formulate this task into sequence labeling.
As the result shows, it outperforms all the participants mentioned in the original paper.

I have cloned your code and tried to reproduce the scores you provided in the table, however, I could not reproduce such good performance. I only changed the model and model type to bert and bert-base-uncased. Then, add model arguments as you mentioned in Readme. Should I adjust anything that you didn't mention in the description?

Best.

**Comment by honghanhh** [comment]
Hi @mengruwu, thank you for your interests in this task. Here, I have just uploaded the whole workflow in README. This code here is only a part of the whole works. I will update the final version as soon as possible. Thank you!
